### ISSUE TITLE
UL: btageff Processor

### ISSUE THREAD

**Issue by ParticleChef** [mcremone/decaf#85]
@ParticleChef I really have a strong preference for adding boolean as attributes of objects. For example, here:

https://github.com/ParticleChef/decaf/blob/forBtagw/analysis/processors/btageff.py#L52

I really prefer this:

https://github.com/mcremone/decaf/blob/master/analysis/processors/btageff.py#L49

_Originally posted by @mcremone in https://github.com/mcremone/decaf/issues/72#issuecomment-1860779095_

**Comment by mcremone** [comment]
Items to be taken care of:

1) Use `hist` instead of `coffea.hist`:

https://github.com/mcremone/decaf/blob/master/analysis/processors/btageff.py#L16-L37
https://github.com/mcremone/decaf/blob/master/analysis/processors/btageff.py#L61-L76

Follow these instructions:

https://github.com/CoffeaTeam/coffea/discussions/705

@alejands will take care of this

2) Check if these still work:

https://github.com/mcremone/decaf/blob/master/analysis/processors/btageff.py#L45
https://github.com/mcremone/decaf/blob/master/analysis/processors/btageff.py#L48-L50

@michaeldmurphy1 will take care of this

3) Adjust `run.py` to be able to run the processor:

https://github.com/mcremone/decaf/blob/master/analysis/run.py#L45-L50

@ParticleChef has already worked on this in the context of another GitHub issue:

https://github.com/mcremone/decaf/issues/81#issuecomment-1873650315

That being said I doubt that `processor.run_uproot_job` is still supported in coffea 0.7.22. @senadurgut can you check?

**Comment by michaeldmurphy1** [comment]
The lines assigned to me still are operational.

**Comment by mcremone** [comment]
Done.
